# 컨테이너 지정
version: "3.9"

# 컨테이너 지정
services:
  mariadb:
     # container_name : 컨테이너의 이름
    container_name: mariadb
    
    # build : 해당 서비스 이미지를 빌드하기 위한 Dockfile이 위치하는 경로를 지정
    build: ./requirements/mariadb/
    
    # 커스텀 네트워크 생성 : docker 컨테이너끼리 통신할 수 있도록 설정하는 옵션
    networks:
      - 42net
    ports:
      - 3306:3306
    
    # 서로 다른 컨테이너들이 하나의 volume을 공유
    volumes:
      - db:/var/lib/mysql
    
    # env_file : 환경 파일
    #            파일이 여러 개라면 리스트 형태로 삽입한다.
    env_file:
      - .env
    restart: always

  wordpress:
    # depends_on 서비스간의 종속성 순서대로 서비스를 시작할 수 있게 설정한다.
    depends_on:
      - mariadb
      - redis
    container_name: wordpress
    build: ./requirements/wordpress/
    networks:
      - 42net
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

  nginx:
    depends_on:
      - wordpress
      - adminer
      - goaccess
      - simple-static-web
    container_name: nginx
    build: ./requirements/nginx/
    networks:
      - 42net
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html/wordpress
      - log:/var/log/nginx
    env_file:
      - .env
    restart: always

  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    networks:
      - 42net
    ports:
      - 6379:6379
    env_file:
      - .env
    restart: always

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
    networks:
      - 42net
    ports:
      - 20:20
      - 21:21
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    networks:
      - 42net
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always

  goaccess:
    container_name: goaccess
    build:
      context: ./requirements/bonus/goaccess
    networks:
      - 42net
    ports:
      - 7000:7000
      - 7890:7890
    volumes:
      - log:/var/log/nginx
    env_file:
      - .env
    restart: always

  simple-static-web:
    container_name: simple-static-web
    build:
      context: ./requirements/bonus/simple-static-web
    networks:
      - 42net
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always


#bridge : network의 default설정 docker container가 이 네트워크 내에서 생성되면
#         각자의 사설ip를 부여받고 같은 네트워크의 컨테이너끼리 통신이 가능
networks:
  42net:
    name: 42net
    driver: bridge

# volume : 도커를 띄우는 환경에 있는 저장공간을 docker 컨테이너의 공간에서 사용하도록 공유
# 서로 다른 컨테이너들이 하나의 volume을 공유
# 공유할 볼륨 정의
volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/sunbchoi/data/db
  wp:
    driver_opts:
      type: none
      o: bind
      device: /home/sunbchoi/data/wp
  log:
    driver_opts:
      type: none
      o: bind
      device: /home/sunbchoi/data/log
